### PR TITLE
Add forever loops

### PR DESCRIPTION
**Pull request by schas002**
- `forever` is for `for(;;)`, an infinite loop

### CODE REVIEW

**Comment by schas002** [comment]
Sadly, I have to refrain from review, and assign @betseg as a collaborator to do it.

**Review by betseg — CHANGES_REQUESTED** [review]
`#define value &` is old. pleas change it to `address`

**Comment by schas002** [comment]
(Don't merge this yet, I just need to add the vocabulary entry...)

**Review by betseg — CHANGES_REQUESTED** [review]
`#define value &` is old. please change it to `address`

**Comment by schas002** [comment]
Will do.

**Comment by schas002** [comment]
Applied changes now

**Comment by schas002** [comment]
help

I have a conflict :cry:

**Comment by schas002** [comment]
Okay now, this PR's branch has conflicts. Don't want to continue the open/close war, but why open? :|

**Comment by betseg** [comment]
i didnt notice i reopened sorry :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
